# Miry
spring:
  application:
    name: PIZZA-SERVICE
  datasource:
    #    driver-class-name: org.h2.Driver
    #    url: jdbc:h2:file:~/data/PizzaServiceDB;AUTO_SERVER=TRUE
    #    username: sa
    #    password: sa
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/PizzaServiceDB
    username: root
    password: root
  jpa:
    #    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 0
  servlet:
    context-path: /api

app:
  rabbitmq:
    add-pizzas-routingkey: q.add-pizzas-to-restaurant
    pizzas-added-routingkey: q.pizzas-added-to-restaurant
    notify-pizzas-added-routingkey: q.notify-pizzas-added-to-restaurant

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka