spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - uri: lb://PIZZA-SERVICE
          predicates:
            - Path=/api/pizzas/**, /api/toppings/**
        - uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/api/restaurants/**. /api/driver/**

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka